export const analyticsEvents = {
  conversionIntentClicked: 'Conversion Intent Clicked',
  conversionSourceClicked: 'Conversion Source Clicked',
  blogJourneyClicked: 'Blog Journey Clicked',
  campaignLandingViewed: 'Campaign Landing Viewed',
  contactFormStarted: 'Contact Form Started',
  contactFormSubmitted: 'Contact Form Submitted',
  contactFormSubmissionFailed: 'Contact Form Submission Failed',
  projectPlannerStarted: 'Project Planner Started',
  projectPlannerStepCompleted: 'Project Planner Step Completed',
  projectBriefSubmitted: 'Project Brief Submitted',
  projectBriefSubmissionFailed: 'Project Brief Submission Failed',
  portfolioVideoPlayed: 'Portfolio Video Played',
  faqQuestionFormStarted: 'FAQ Question Form Started',
  faqQuestionSubmitted: 'FAQ Question Submitted',
  faqQuestionSubmissionFailed: 'FAQ Question Submission Failed',
} as const
